"""Add course catalog tables

Revision ID: 45d42227d875
Revises: 
Create Date: 2025-10-13 10:07:19.109405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d42227d875'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignments_id', table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_courses_id', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_study_sessions_id', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index('ix_course_catalog_id', table_name='course_catalog')
    op.drop_index('ix_course_catalog_number', table_name='course_catalog')
    op.drop_index('ix_course_catalog_semester', table_name='course_catalog')
    op.drop_index('ix_course_catalog_subject', table_name='course_catalog')
    op.drop_index('ix_course_catalog_year', table_name='course_catalog')
    op.drop_table('course_catalog')
    op.drop_index('ix_availability_slots_id', table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index('ix_course_sections_id', table_name='course_sections')
    op.drop_table('course_sections')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('course_sections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crn', sa.VARCHAR(), nullable=False),
    sa.Column('days', sa.VARCHAR(), nullable=True),
    sa.Column('times', sa.VARCHAR(), nullable=True),
    sa.Column('instructor', sa.VARCHAR(), nullable=True),
    sa.Column('course_catalog_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_catalog_id'], ['course_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_sections_id', 'course_sections', ['id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.VARCHAR(), nullable=False),
    sa.Column('end_time', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_availability_slots_id', 'availability_slots', ['id'], unique=False)
    op.create_table('course_catalog',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(), nullable=False),
    sa.Column('number', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('credit_hours', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('semester', sa.VARCHAR(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_course_catalog_year', 'course_catalog', ['year'], unique=False)
    op.create_index('ix_course_catalog_subject', 'course_catalog', ['subject'], unique=False)
    op.create_index('ix_course_catalog_semester', 'course_catalog', ['semester'], unique=False)
    op.create_index('ix_course_catalog_number', 'course_catalog', ['number'], unique=False)
    op.create_index('ix_course_catalog_id', 'course_catalog', ['id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('end_time', sa.DATETIME(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_sessions_id', 'study_sessions', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=False),
    sa.Column('estimated_hours', sa.FLOAT(), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=6), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_id', 'assignments', ['id'], unique=False)
    # ### end Alembic commands ###
